// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'constants.dart';
import 'features/firebase_config_store.dart';

/// Helper to atomically resolve Firebase config from secure storage or .env
Future<Map<String, String>> _resolveFirebaseConfig() async {
  final secureOverrides = await FirebaseConfigStore.loadRuntimeConfig();
  if (secureOverrides.isNotEmpty) {
    return {
      'apiKey': secureOverrides[firebaseApiKeyPref] ?? '',
      'appId': secureOverrides[firebaseAppIdPref] ?? '',
      'messagingSenderId': secureOverrides[firebaseSenderIdPref] ?? '',
      'projectId': secureOverrides[firebaseProjectIdPref] ?? '',
      'storageBucket': secureOverrides[firebaseStorageBucketPref] ?? '',
    };
  }

  // Use .env for all fields
  final envApiKey = dotenv.env['FIREBASE_API_KEY'];
  final envAppId = dotenv.env['FIREBASE_APP_ID'];
  final envSenderId = dotenv.env['FIREBASE_MESSAGING_SENDER_ID'];
  final envProjectId = dotenv.env['FIREBASE_PROJECT_ID'];
  final envStorageBucket = dotenv.env['FIREBASE_STORAGE_BUCKET'];

  if (envApiKey == null ||
      envApiKey.isEmpty ||
      envAppId == null ||
      envAppId.isEmpty ||
      envSenderId == null ||
      envSenderId.isEmpty ||
      envProjectId == null ||
      envProjectId.isEmpty ||
      envStorageBucket == null ||
      envStorageBucket.isEmpty) {
    throw ArgumentError('Missing Firebase config (check Settings or .env)');
  }

  return {
    'apiKey': envApiKey,
    'appId': envAppId,
    'messagingSenderId': envSenderId,
    'projectId': envProjectId,
    'storageBucket': envStorageBucket,
  };
}

/// Helper to get Firebase config from SharedPreferences or .env
/// Kept for backward compatibility with tests
Future<String> getConfig(String key, String prefKey) async {
  final config = await _resolveFirebaseConfig();
  final keyMap = {
    'FIREBASE_API_KEY': 'apiKey',
    'FIREBASE_APP_ID': 'appId',
    'FIREBASE_MESSAGING_SENDER_ID': 'messagingSenderId',
    'FIREBASE_PROJECT_ID': 'projectId',
    'FIREBASE_STORAGE_BUCKET': 'storageBucket',
  };
  return config[keyMap[key]]!;
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static Future<FirebaseOptions> get macos async {
    final config = await _resolveFirebaseConfig();
    return FirebaseOptions(
      apiKey: config['apiKey']!,
      appId: config['appId']!,
      messagingSenderId: config['messagingSenderId']!,
      projectId: config['projectId']!,
      storageBucket: config['storageBucket']!,
      iosBundleId: 'com.example.browser',
    );
  }
}
