// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Helper to get Firebase config from SharedPreferences or .env
Future<String> getConfig(String key) async {
  final prefs = await SharedPreferences.getInstance();
  final prefKey = 'firebase_$key';
  final prefValue = prefs.getString(prefKey);

  if (prefValue != null && prefValue.isNotEmpty) {
    return prefValue;
  }

  final envValue = dotenv.env[key];
  if (envValue == null || envValue.isEmpty) {
    throw ArgumentError('Missing Firebase config: $key (check Settings or .env)');
  }
  return envValue;
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static Future<FirebaseOptions> get macos async => FirebaseOptions(
        apiKey: await getConfig('FIREBASE_API_KEY'),
        appId: await getConfig('FIREBASE_APP_ID'),
        messagingSenderId: await getConfig('FIREBASE_MESSAGING_SENDER_ID'),
        projectId: await getConfig('FIREBASE_PROJECT_ID'),
        storageBucket: await getConfig('FIREBASE_STORAGE_BUCKET'),
        iosBundleId: 'com.example.browser',
      );
}
