name: 'Setup Flutter'
description: 'Sets up Flutter environment'

inputs:
  flutter-version:
    description: 'Flutter version to install'
    required: true
    default: '3.38.3'

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}